name: Deploy Node.js Backend to Firebase Functions

on:
  push:
    branches:
      - main # Adjust this based on your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the same version as your functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools # Install Firebase CLI globally

      - name: Install dependencies
        run: cd task_manager_backend && npm install 

      - name: Deploy to Firebase Functions
        run: cd task_manager_backend && npm run deploy --token ${{ secrets.FIREBASE_TOKEN }}
